# Generated by Django 4.1.2 on 2022-10-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiAI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='querys',
            name='respuesta',
            field=models.CharField(blank=True, default='some_value', editable=False, max_length=400),
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
    ]
